print("Challenge 7")
import turtle
window = turtle.Screen()
marty = turtle.Turtle()
marty.forward(1500)
marty.left(90)
marty.forward(800)
marty.left(90)
marty.forward(1500)
marty.left(90)
marty.forward(800)